### ISSUE TITLE
Attaching audio to a Ghost blog throws an error

### ISSUE THREAD

**Issue by bmann** [fission-codes/landing-page#90]
Publishing log here https://github.com/fission-codes/landing-page/actions/runs/5602693805/jobs/10248288600

```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] `src` is a required argument to the eleventy-img utility (can be a String file path, String URL, or Buffer). (via Error)
[11ty] 
[11ty] Original error stack trace: Error: `src` is a required argument to the eleventy-img utility (can be a String file path, String URL, or Buffer).
[11ty]     at new Image (/home/runner/work/landing-page/landing-page/node_modules/@11ty/eleventy-img/img.js:119:13)
[11ty]     at queueImage (/home/runner/work/landing-page/landing-page/node_modules/@11ty/eleventy-img/img.js:623:13)
[11ty]     at imageShortcode (/home/runner/work/landing-page/landing-page/.eleventy.js:36:24)
[11ty]     at /home/runner/work/landing-page/landing-page/.eleventy.js:201:44
[11ty]     at Array.forEach (<anonymous>)
[11ty]     at Object.posts (/home/runner/work/landing-page/landing-page/.eleventy.js:195:16)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async TemplateMap.getUserConfigCollection (/home/runner/work/landing-page/landing-page/node_modules/@11ty/eleventy/src/TemplateMap.js:556:18)
[11ty]     at async TemplateMap.setCollectionByTagName (/home/runner/work/landing-page/landing-page/node_modules/@11ty/eleventy/src/TemplateMap.js:258:39)
[11ty]     at async TemplateMap.initDependencyMap (/home/runner/work/landing-page/landing-page/node_modules/@11ty/eleventy/src/TemplateMap.js:284:9)
```

I think this is the image resizing script attempting to resize an audio file.

This needs to detect `.m4a` extensions and just publish them as is to the build tree.

**Comment by bmann** [comment]
What a wild trip it's been! If you don't include an image, we get an error. Which is fine. But now we have a custom podcast feed. Closing.
